### ISSUE TITLE
大佬帮忙，test方法发消息，然后启动工程，接收不到消息,，程里面也新建类了，用命令可以收到

### ISSUE THREAD

**Issue by bergkamp2008999** [Swayingleaves/spring-boot-starter-pulsar#1]
新建类:
package com.swayingleaves.springbootstarterpulsar.pulsar;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class ReceiveDataService {

    @PulsarConsumer(topic ="#consumers[0]",clazz = Serialization.JSON)
    public void receive(JSONObject msg){
        log.info("receive msg:{}",msg);
    }

    @PulsarConsumer(topic ="#consumers[1]",clazz = Serialization.STRING)
    public void receive(String msg){
        log.info("receive msg:{}",msg);
    }

    @PulsarConsumer(topic ="#consumers[2]",clazz = Serialization.JSON_ARRAY)
    public void receive(JSONArray msg){
        log.info("receive msg:{}",msg);
    }

}

配置文件：
pulsar:
  # 服务器地址
  serviceUrl: pulsar://172.26.2.129:6650
  # io线程数默认10
  ioThreads: 10
  # listener线程数默认10
  listenerThreads: 10
  # JSON/JSONArray格式数据的生产者的topic，多个使用英文逗号分隔
  jsonProducers: producer1-json
  # string格式数据的生产者的topic，多个使用英文逗号分隔
  stringProducers: consumers2
  # 消费者topic，多个使用英文逗号分隔
  consumers: consumers1,consumers2,consumers3

test方法：
    @Test
    void sendStrMsg() throws PulsarClientException {
        pulsarTemplate.sendStringMsg("consumers2","wo fa chule");
    }

用命令可以收到：
 ./pulsar-client consume consumers2 -s "first-subscription"

**Comment by Swayingleaves** [comment]
我现在没有可以测试的环境了sorry，可能调不了，你先这样
1、配置里
```yml
pulsar:
  # 服务器地址
  serviceUrl: pulsar://172.26.2.129:6650
  # io线程数默认10
  ioThreads: 10
  # listener线程数默认10
  listenerThreads: 10 
```

其他的不用配置

2、service里只写启动string的消费者，注意topic直接写
```java
@service
@slf4j
public class ReceiveDataService {

  @PulsarConsumer(topic ="test_string_topic",clazz = Serialization.STRING)
  public void receive(String msg){
      log.info("receive msg:{}",msg);
  }

}
```

3、测试类里
```java
    @Autowired
    PulsarTemplate pulsarTemplate;
   
    @Test
    void sendStrMsg() throws PulsarClientException {
        pulsarTemplate.sendStringMsg("test_string_topic","str");
    }

```
4、启动项目，运行测试类
5、查看log是否打印

**Comment by Swayingleaves** [comment]
> 新建类:
> package com.swayingleaves.springbootstarterpulsar.pulsar;
> 
> import com.alibaba.fastjson.JSONArray;
> import com.alibaba.fastjson.JSONObject;
> import lombok.extern.slf4j.Slf4j;
> import org.springframework.stereotype.Service;
> 
> @service
> @slf4j
> public class ReceiveDataService {
> 
> ```
> @PulsarConsumer(topic ="#consumers[0]",clazz = Serialization.JSON)
> public void receive(JSONObject msg){
>     log.info("receive msg:{}",msg);
> }
> 
> @PulsarConsumer(topic ="#consumers[1]",clazz = Serialization.STRING)
> public void receive(String msg){
>     log.info("receive msg:{}",msg);
> }
> 
> @PulsarConsumer(topic ="#consumers[2]",clazz = Serialization.JSON_ARRAY)
> public void receive(JSONArray msg){
>     log.info("receive msg:{}",msg);
> }
> ```
> 
> }
> 
> 配置文件：
> pulsar:
> 
> # 服务器地址
> serviceUrl: pulsar://172.26.2.129:6650
> 
> # io线程数默认10
> ioThreads: 10
> 
> # listener线程数默认10
> listenerThreads: 10
> 
> # JSON/JSONArray格式数据的生产者的topic，多个使用英文逗号分隔
> jsonProducers: producer1-json
> 
> # string格式数据的生产者的topic，多个使用英文逗号分隔
> stringProducers: consumers2
> 
> # 消费者topic，多个使用英文逗号分隔
> consumers: consumers1,consumers2,consumers3
> 
> test方法：
> @test
> void sendStrMsg() throws PulsarClientException {
> pulsarTemplate.sendStringMsg("consumers2","wo fa chule");
> }
> 
> 用命令可以收到：
> ./pulsar-client consume consumers2 -s "first-subscription"

**Comment by Swayingleaves** [comment]
> 新建类:
> package com.swayingleaves.springbootstarterpulsar.pulsar;
> 
> import com.alibaba.fastjson.JSONArray;
> import com.alibaba.fastjson.JSONObject;
> import lombok.extern.slf4j.Slf4j;
> import org.springframework.stereotype.Service;
> 
> @service
> @slf4j
> public class ReceiveDataService {
> 
> ```
> @PulsarConsumer(topic ="#consumers[0]",clazz = Serialization.JSON)
> public void receive(JSONObject msg){
>     log.info("receive msg:{}",msg);
> }
> 
> @PulsarConsumer(topic ="#consumers[1]",clazz = Serialization.STRING)
> public void receive(String msg){
>     log.info("receive msg:{}",msg);
> }
> 
> @PulsarConsumer(topic ="#consumers[2]",clazz = Serialization.JSON_ARRAY)
> public void receive(JSONArray msg){
>     log.info("receive msg:{}",msg);
> }
> ```
> 
> }
> 
> 配置文件：
> pulsar:
> 
> # 服务器地址
> serviceUrl: pulsar://172.26.2.129:6650
> 
> # io线程数默认10
> ioThreads: 10
> 
> # listener线程数默认10
> listenerThreads: 10
> 
> # JSON/JSONArray格式数据的生产者的topic，多个使用英文逗号分隔
> jsonProducers: producer1-json
> 
> # string格式数据的生产者的topic，多个使用英文逗号分隔
> stringProducers: consumers2
> 
> # 消费者topic，多个使用英文逗号分隔
> consumers: consumers1,consumers2,consumers3
> 
> test方法：
> @test
> void sendStrMsg() throws PulsarClientException {
> pulsarTemplate.sendStringMsg("consumers2","wo fa chule");
> }
> 
> 用命令可以收到：
> ./pulsar-client consume consumers2 -s "first-subscription"

我现在没有可以测试的环境了sorry，可能调不了，你先这样
1、配置里
```yml
pulsar:
  # 服务器地址
  serviceUrl: pulsar://172.26.2.129:6650
  # io线程数默认10
  ioThreads: 10
  # listener线程数默认10
  listenerThreads: 10 
```

其他的不用配置

2、service里只写启动string的消费者，注意topic直接写
```java
@service
@slf4j
public class ReceiveDataService {

  @PulsarConsumer(topic ="test_string_topic",clazz = Serialization.STRING)
  public void receive(String msg){
      log.info("receive msg:{}",msg);
  }

}
```

3、测试类里
```java
    @Autowired
    PulsarTemplate pulsarTemplate;
   
    @Test
    void sendStrMsg() throws PulsarClientException {
        pulsarTemplate.sendStringMsg("test_string_topic","str");
    }

```
4、启动项目，运行测试类
5、查看log是否打印

**Comment by bergkamp2008999** [comment]
谢谢哥们，我试试
